// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

//登录界面
void ui_Screen1_screen_init(P_Cli p_cli)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui__temporary_image);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -16);
    lv_obj_set_y(ui_Image1, 5);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);  //背景图片
    lv_image_set_src(ui_Image2, &ui_img_login_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_Image2, -1);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER); 
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_Screen1);   //图标
    lv_image_set_src(ui_Image5, &ui_img_user_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image5, -330);
    lv_obj_set_y(ui_Image5, -148);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Screen1);   //图标
    lv_image_set_src(ui_Image6, &ui_img_459333202);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image6, -329);
    lv_obj_set_y(ui_Image6, -82);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 72);
    lv_obj_set_height(ui_Button1, 47);
    lv_obj_set_x(ui_Button1, -261);
    lv_obj_set_y(ui_Button1, -18);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 72);
    lv_obj_set_height(ui_Button2, 47);
    lv_obj_set_x(ui_Button2, -163);
    lv_obj_set_y(ui_Button2, -18);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // 设置文本颜色为红色
    lv_color_t red = lv_color_hex(0xFF0000);  // 创建红色

    Init_Freetype();  //初始化字库
    Init_Freetype1();
    Init_Freetype2();
    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_center(ui_Label1);
    lv_label_set_chinese(ui_Label1,"登录");

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_center(ui_Label2);
    lv_label_set_chinese(ui_Label2,"注册");

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -211);
    lv_obj_set_y(ui_Label3, -200);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Label3, red, LV_STATE_DEFAULT);
    lv_label_set_chinese(ui_Label3,"聊天系统登录");

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 806);
    lv_obj_set_height(ui_Keyboard1, 218);
    lv_obj_set_x(ui_Keyboard1, 2);
    lv_obj_set_y(ui_Keyboard1, 134);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1,LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_CLICKED,p_cli);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_CLICKED, NULL);

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 207);
    lv_obj_set_height(ui_TextArea1, 44);
    lv_obj_set_x(ui_TextArea1, -205);
    lv_obj_set_y(ui_TextArea1, -150);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "username:");
    lv_obj_add_event_cb( ui_TextArea1 ,text_event1,LV_EVENT_ALL,ui_Keyboard1);

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, 207);
    lv_obj_set_height(ui_TextArea2, 44);
    lv_obj_set_x(ui_TextArea2, -206);
    lv_obj_set_y(ui_TextArea2, -83);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "password:");
    lv_obj_add_event_cb( ui_TextArea2,text_event1,LV_EVENT_ALL, ui_Keyboard1);
}
