// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

//群聊界面
void ui_Screen5_screen_init(P_Cli p_cli)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Screen5);
    lv_image_set_src(ui_Image14, &ui_img_wukong_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea5 = lv_textarea_create(ui_Screen5);  //消息输入框
    lv_obj_set_width(ui_TextArea5, 320);
    lv_obj_set_height(ui_TextArea5, 40);
    lv_obj_set_x(ui_TextArea5, -9);
    lv_obj_set_y(ui_TextArea5, -213);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);

    ui_Button5 = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_Button5, 80);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 189);
    lv_obj_set_y(ui_Button5, -213);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Button5,snd_btn_all, LV_EVENT_CLICKED,p_cli);

    lv_obj_t *snd_label = lv_label_create(ui_Button5);
    lv_label_set_chinese(snd_label,"发送");

    ui_Label4 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 194);
    lv_obj_set_y(ui_Label4, -215);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "");

    ui_TabView1 = lv_tabview_create(ui_Screen5);  //显示框
    lv_tabview_set_tab_bar_size(ui_TabView1, 50);
    lv_obj_set_width(ui_TabView1, 550);
    lv_obj_set_height(ui_TabView1, 400);
    lv_obj_set_x(ui_TabView1, 110);
    lv_obj_set_y(ui_TabView1, -20);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_tabview_add_tab_chinese(ui_TabView1,"修真聊天群");

    label_tabview = lv_label_create(ui_TabView1);  // 在 Tab 1 中创建一个标签


    ui_Image18 = lv_image_create(ui_Screen5);
    lv_image_set_src(ui_Image18, &ui_img_1636180821);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image18, 379);
    lv_obj_set_y(ui_Image18, -221);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Image18,exit_to_main,LV_EVENT_CLICKED, p_cli);

    ui_Keyboard4 = lv_keyboard_create(ui_Screen5);
    lv_obj_set_width(ui_Keyboard4, 806);
    lv_obj_set_height(ui_Keyboard4, 187);
    lv_obj_set_x(ui_Keyboard4, 0);
    lv_obj_set_y(ui_Keyboard4, 143);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4,LV_OBJ_FLAG_HIDDEN); //隐藏键盘
    lv_obj_add_event_cb(ui_TextArea5,text_event4, LV_EVENT_ALL, ui_Keyboard4);

    lv_obj_add_flag(ui_Screen4,LV_OBJ_FLAG_HIDDEN); //隐藏登录界面
}
