// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

//主界面
void ui_Screen3_screen_init(P_Cli p_cli)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Image11, &ui_img_main_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Image15, &ui_img_1810374608);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image15, -282);
    lv_obj_set_y(ui_Image15, 0);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Image17, &ui_img_944254084);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image17, 289);
    lv_obj_set_y(ui_Image17, 0);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Image19, &ui_img_600691551);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image19, 379);
    lv_obj_set_y(ui_Image19, -222);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Image21, &ui_img_695783995);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image21, 14);
    lv_obj_set_y(ui_Image21, 0);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image15, ui_event_Image15, LV_EVENT_ALL, p_cli);
    lv_obj_add_event_cb(ui_Image17, ui_event_Image17, LV_EVENT_ALL, p_cli);
    lv_obj_add_event_cb(ui_Image19, ui_event_Image19, LV_EVENT_ALL, p_cli);
    lv_obj_add_event_cb(ui_Image21, ui_event_Image21, LV_EVENT_ALL, p_cli);
}
