// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

//私聊界面
void ui_Screen4_screen_init(P_Cli p_cli)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image13, &ui_img_private_chat_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Screen4,LV_OBJ_FLAG_HIDDEN); //隐藏chat界面

    lv_obj_t *button=lv_button_create(ui_Screen4);
    lv_obj_set_size(button,80,40);
    lv_obj_set_align(button,LV_ALIGN_CENTER);
    lv_obj_t *label_button=lv_label_create(button);
    // 设置文本颜色为红色
    lv_color_t red = lv_color_hex(0xFF0000);  // 创建红色
    lv_label_set_chinese(label_button,"刷新");
    lv_obj_set_style_text_color(label_button, red, LV_STATE_DEFAULT);
    lv_obj_add_event_cb(button,reset_online_event, LV_EVENT_CLICKED,p_cli); //在线人员刷新按钮

    textarea1=lv_textarea_create(ui_Screen4);  //消息输入框
    lv_obj_set_size(textarea1,300,50);
    lv_obj_align(textarea1,LV_ALIGN_TOP_MID,50,0);
    lv_obj_add_flag(textarea1,LV_OBJ_FLAG_HIDDEN);

    send_button=lv_button_create(ui_Screen4);  //发送按钮
    lv_obj_set_size(send_button,80,50);
    lv_obj_align_to(send_button,textarea1,LV_ALIGN_OUT_RIGHT_TOP,0,0);
    lv_obj_t *send_label=lv_label_create(send_button);
    lv_label_set_chinese(send_label,"发送");
    lv_obj_add_event_cb(send_button,send_msg_event,LV_EVENT_CLICKED, p_cli);
    lv_obj_add_flag(send_button,LV_OBJ_FLAG_HIDDEN);

    ui_Image18 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image18, &ui_img_1636180821);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image18, 379);
    lv_obj_set_y(ui_Image18, -221);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Image18,exit_to_mains,LV_EVENT_CLICKED, p_cli);

    //创建键盘
    ui_Keyboard3 = lv_keyboard_create(ui_Screen4);
    lv_obj_set_width(ui_Keyboard3, 806);
    lv_obj_set_height(ui_Keyboard3, 218);
    lv_obj_set_x(ui_Keyboard3, 2);
    lv_obj_set_y(ui_Keyboard3, 134);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3,LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_event_cb(textarea1,text_event3, LV_EVENT_ALL, ui_Keyboard3);
}

