// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

//注册界面
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image3, &ui__temporary_image);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -2);
    lv_obj_set_y(ui_Image3, 15);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image4, &ui_img_register_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -299);
    lv_obj_set_y(ui_Button3, -2);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -172);
    lv_obj_set_y(ui_Button4, -2);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

        // 设置文本颜色为红色
    lv_color_t red = lv_color_hex(0xFF0000);  // 创建红色

    lv_button_t *ui_Button5=lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_pos(ui_Button5,700,0);

    lv_label_t *ui_Label5 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_center(ui_Label5);
    lv_label_set_chinese(ui_Label5,"返回登录");

    ui_TextArea3 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea3, 267);
    lv_obj_set_height(ui_TextArea3, 51);
    lv_obj_set_x(ui_TextArea3, -229);
    lv_obj_set_y(ui_TextArea3, -150);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "username");

    ui_TextArea4 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea4, 267);
    lv_obj_set_height(ui_TextArea4, 51);
    lv_obj_set_x(ui_TextArea4, -229);
    lv_obj_set_y(ui_TextArea4, -84);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "password");

    ui_Keyboard2 = lv_keyboard_create(ui_Screen2);
    lv_obj_set_width(ui_Keyboard2, 805);
    lv_obj_set_height(ui_Keyboard2, 203);
    lv_obj_set_x(ui_Keyboard2, 1);
    lv_obj_set_y(ui_Keyboard2, 140);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2,LV_OBJ_FLAG_HIDDEN); //隐藏
    lv_obj_add_event_cb( ui_TextArea3 ,text_event2,LV_EVENT_ALL,ui_Keyboard2);
    lv_obj_add_event_cb( ui_TextArea4 ,text_event2,LV_EVENT_ALL,ui_Keyboard2);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);



    lv_label_t *ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_center(ui_Label3);
    lv_label_set_chinese(ui_Label3,"注册");

    lv_label_t *ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_center(ui_Label4);
    lv_label_set_chinese(ui_Label4,"重置");

    lv_label_t *ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -231);
    lv_obj_set_y(ui_Label6, -200);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Label6, red, LV_STATE_DEFAULT);
    lv_label_set_chinese(ui_Label6,"聊天系统注册");


    ui_Image7 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image7, &ui_img_459333202);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image7, -379);
    lv_obj_set_y(ui_Image7, -82);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image8, &ui_img_user_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image8, -379);
    lv_obj_set_y(ui_Image8, -146);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

    lv_obj_add_flag(ui_Screen2,LV_OBJ_FLAG_HIDDEN);  //隐藏注册界面
}
